version: '3.8'
services:
  app:
    image: sunil3gs98/secretesanta-generator:v1.1.0
    ports:
      - "8080:8080"
    container_name: santa
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/santadb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_POST: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: santadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
