apiVersion: v1
kind: Service
metadata:
  name: santa-app-service
  namespace: sunil3gs98
  labels:
    app: santa
  annotations:
    prometheus.io/scrape: "true"        # Enable scraping
    prometheus.io/path: "/actuator/prometheus"  # Metrics path
    prometheus.io/port: "8080"          # Port where metrics are exposed
spec:
  selector:
    app: santa
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
