apiVersion: v1
kind: Service
metadata:
  name: santa-db-service
  labels:
    app: santa-db
spec:
  selector:
    app: santa-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
