apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: sunil3gs98
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # or NodePort if you prefer
